version: "2"

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (*os/exec.Cmd).Wait
        - (*os/exec.Cmd).Process.Kill
        - io.Copy
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: _test\.go
        linters:
          - unused
      - linters:
          - staticcheck
        text: "SA1019:.*viewport\\.(LineUp|LineDown|HalfViewUp|HalfViewDown)"

formatters:
  enable:
    - gofmt
    - goimports
